### ISSUE TITLE
Doesn't work in Gitlab CI

### ISSUE THREAD

**Issue by oliv3** [m13253/ltowrapper#2]
Hi, thanks for this script. I have an issue though when using it in Gitlab CI:

```
$ ./LTOWrapper
Created "ar"
Created "nm"
Created "ranlib"
Created "cc"
Created "c++"
Created "gcc"
Created "g++"
Starting "/bin/bash" shell, type "exit" when you finish.
bash: cannot set terminal process group (1): Inappropriate ioctl for device
bash: no job control in this shell
root@runner-0277ea0f-project-8572288-concurrent-0:/builds/lebiniou/lebiniou# exit
removed '/tmp/ltowrapper.pqyRo9oUBM/gcc-ranlib'
removed '/tmp/ltowrapper.pqyRo9oUBM/cc'
removed '/tmp/ltowrapper.pqyRo9oUBM/gcc-nm'
removed '/tmp/ltowrapper.pqyRo9oUBM/gcc'
removed '/tmp/ltowrapper.pqyRo9oUBM/gcc-ar'
removed '/tmp/ltowrapper.pqyRo9oUBM/c++'
removed '/tmp/ltowrapper.pqyRo9oUBM/nm'
removed '/tmp/ltowrapper.pqyRo9oUBM/ar'
removed '/tmp/ltowrapper.pqyRo9oUBM/ranlib'
removed '/tmp/ltowrapper.pqyRo9oUBM/g++'
removed directory '/tmp/ltowrapper.pqyRo9oUBM'
```

Any workaround ?

**Comment by m13253** [comment]
> bash: cannot set terminal process group (1): Inappropriate ioctl for device
> bash: no job control in this shell

I think this message is because Gitlab CI is not using a PTY for output redirection.
This is only a warning. I think you can ignore it.

**Comment by oliv3** [comment]
As you can see this error throws immediately a shell "exit".

**Comment by m13253** [comment]
Oh I see. Please try
```
$ ./LTOWrapper bash
```
and see whether it works.

**Comment by oliv3** [comment]
It looks [OK](https://gitlab.com/lebiniou/lebiniou/-/jobs/1027345762#L3609) now, thanks ! Maybe worth documenting ?

**Comment by m13253** [comment]
> Maybe worth documenting ?

Sorry for that, I will do it later. (I'm on travel.)
Currently I only wrote this in the `--help` page:
```
Usage: Interactive mode:   $0
       Batch mode:         $0 - command
       Cross compile mode: $0 host-triple command
```

**Comment by m13253** [comment]
If you are using LTOWrapper in an automated environment, I suggest that you put everything you want to run inside the environment into a script.

Then you can call `./LTOWrapper - ./yourscript.sh`. Note that `-`, that's for the cross-compile triple (e.g. `x86_64-w64-mingw32`). If you don't need cross-compiling, put a `-` there.

**Comment by oliv3** [comment]
I do [this](https://gitlab.com/lebiniou/lebiniou/-/blob/json_config_uglifyjs_cleancss/.gitlab-ci.yml#L184-208), works like a charm. (Wrong link updated :)

**Comment by m13253** [comment]
I am not sure whether your it can work.
First, your `./configure` is not covered by LTOWrapper. So the configuration script may not select the correct compiler.
Second, through the log I didn't see LTOWrapper being called once.
Would you please double check it?

**Comment by oliv3** [comment]
Oops, good catch. Updated [here](https://gitlab.com/lebiniou/lebiniou/-/blob/json_config_uglifyjs_cleancss/.gitlab-ci.yml#L184-208). But it looks like it still [fails](https://gitlab.com/lebiniou/lebiniou/-/jobs/1027459824#L3275)...

**Comment by m13253** [comment]
> But it looks like it still [fails](https://gitlab.com/lebiniou/lebiniou/-/jobs/1027459824#L3275)...

Pay attention that CI is not interactive, if you call `./LTOWrapper bash`, it actually spawns a bash and waits for your keyboard input.
Since there is no keyboard, this may fail.

Anyway I suggest that you either
(a) write a script,
(b) create a here-document using bash then plug it in,
(c) use something like `CC=gcc-10 ./LTOWrapper - bash -c './configure && make'`

**Comment by oliv3** [comment]
Damn logs. [Here](https://storage.googleapis.com/gitlab-gprd-artifacts/65/e1/65e1e64b7f5667275a6bd7d2ade5bcaa89c62c2b77b3597c86746c9861dade18/2021_02_12/1027459824/1120803571/job.log?response-content-type=text%2Fplain%3B%20charset%3Dutf-8&response-content-disposition=inline&GoogleAccessId=gitlab-object-storage-prd@gitlab-production.iam.gserviceaccount.com&Signature=Cg9FWhs2NLacemJ7YTu40VUePPd6ICGvSDRPER36qub%2BMCOYwn6KbdGPtIRv%0AHZyrXk1qLzqePP2wYkX1e9tYyxqJHXQbJ7fmjEuyax3PKwoY%2F0PNdE9ISXE1%0AaP6TBw4AydPjAvORDRouDtI5%2BFGQIDw5xHfsfLNAGeeyBGR3x%2BPw8FqOjREf%0Ay3Hs44qKReURn%2FPL0Y%2BRQ7igYWKDKl3zT6GI8RmyjmLC6SxwrTkJfK4N15l9%0A9tWivod7ozTLyXzcJzLBSkMlLLPIkCca3v3oeeYTvRIW%2BrU2LUSGf2xqqatK%0A1ni9%2FO82qvK5PrplZ2dFxpjUPoPjJM2vz2MFnxZx%2FA%3D%3D&Expires=1613161345).

**Comment by oliv3** [comment]
Ok, let my try (c).

**Comment by oliv3** [comment]
[There](https://gitlab.com/lebiniou/lebiniou/-/jobs/1027483008/raw) you go :)

**Comment by oliv3** [comment]
Updated [.gitlab-ci.yml](https://gitlab.com/lebiniou/lebiniou/-/blob/json_config_uglifyjs_cleancss/.gitlab-ci.yml#L184-206).

**Comment by m13253** [comment]
Check this line:
```
checking for gcc... /tmp/ltowrapper.ml4TbHWtBL/gcc
```
Yay! It worked.

**Comment by oliv3** [comment]
Yep, saw that :)

**Comment by m13253** [comment]
By the way, I think my script ignores your request for gcc-10.
If you really need gcc-10, you might need to make some `PATH` tweaks or symlinks to make sure `which gcc` can point to your gcc-10.

**Comment by oliv3** [comment]
Right, I'll move `CC=gcc-10` before `./configure`. I guess this should work ?

**Comment by m13253** [comment]
> Right, I'll move `CC=gcc-10` before `./configure`. I guess this should work ?

This should work as long as you don't care whether it is gcc-10 or older versions.
If you really need gcc-10, you perhaps need to do something.

**Comment by oliv3** [comment]
In fact, I don't need to do anything. gcc-10 is the default compiler in Debian/sid.

**Comment by oliv3** [comment]
```
$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
```

**Comment by m13253** [comment]
That's great!

**Comment by oliv3** [comment]
Now, some [advertising](https://biniou.net) :)
